### ISSUE TITLE
CRAN comments #1

### ISSUE THREAD

**Issue by nk027** [nk027/bvar#11]
> Thanks,
> 
> Please always write references in the form
> authors (year) <doi:...>
> authors (year) <arXiv:...>
> authors (year, ISBN:...)
> with no space after 'doi:', 'arXiv:' and angle brackets for auto-linking.
> 
> Please provide small executable examples in all your exported functions'
> Rd files to illustrate the use of the exported function but also enable
> automatic testing.
> 
> Please fix and resubmit.
> 
> Best,
> Martina Schmirl

**Comment by nk027** [comment]
- Maybe we should drop ´"´ in the call at https://github.com/nk027/bvar/blob/b37ab6079ecb66937b60311530cdc11cb801ae62/man/bv_priors.Rd#L38 

- `plot.bvar` is missing an example
- `print.bvar` is missing an example
- Couldn't find the reference issue.

**Comment by oDNAudio** [comment]
done with the changes, however also unsure about the references. added them as url to the references, lets see what happens

**Comment by nk027** [comment]
Danke, ist resubmitted!
