### ISSUE TITLE
Implement Forecast

### ISSUE THREAD

**Issue by nk027** [nk027/bvar#2]
- [x] conditional
- [x] unconditional

**Comment by nk027** [comment]
As of ecefd7bd2c73978bb5ff718330829b396418a968 this is largely implemented. Testing and having a look at the API is still necessary.

**Comment by oDNAudio** [comment]
Added conditional forecasts to also be implemented in `bvar()` with [`2b2fe17`](https://github.com/nk027/bvar/commit/2b2fe17c4015ca1db930630b0026b9287502f9aa)
