### ISSUE TITLE
Consider naming scheme

### ISSUE THREAD

**Issue by nk027** [nk027/bvar#20]
The prefix `bv_` makes it rather easy to find functions associated with the package and allows for some extra options without parameter-clutter. However, it is non-standard and might prove to be an entry-barrier, especially in conjunction with standard S3 methods.

Due to compatibility the functions need to stay anyway. It might make sense to move the standard functionalities to classic names and keep the naming scheme as shortcuts and for specific functions (e.g. prior creation and other settings).

**Comment by oDNAudio** [comment]
I would also suggest to change the prefix for the several plotting functions but to keep it for the ones needed for setting up the model (priors, fcast, irf,...) because it just makes it easier to group all functions that are needed before running a model and adjusting it

**Comment by nk027** [comment]
I second that. Closing this issue as of 0dfcce2416eee4073f3ae524c05bc1e2b497aa35.

Steps taken:
- Constructors (i.e. `bv_priors`, `bv_mh`, `bv_irf`, ...) remain as is.
- Plotting functions (`bv_plot`, `bv_plot_trace`, `bv_plot_irf`, ...) have been deprecated.
- Plots and other outputs are now accessed and modified via the included methods (e.g. `plot`, `predict`, `density`, ...).
