### ISSUE TITLE
More plotting improvements

### ISSUE THREAD

**Issue by nk027** [nk027/bvar#29]
The plotting method of our density class now supports plotting the coefficient densities. This should also be possible for the standard plotting method.

It might make sense to reconsider the naming scheme -- we currently have parameters `vars`, `vars_impulse`, `vars_response`, `var_dep` (dependent), `vars_ind` (independent).

I guess we should call all of the latter ones the same way (established one is preferable and interpretation of dependent and response variable is similar).
`vars` is a bit weird, as it is used for the variables to forecast and for hyperparameters to plot...

**Comment by oDNAudio** [comment]
I am not sure if plotting the coefficient densities makes sense, at least in the way achieved up to now.

Now it basically plots the density over all coefficients but to be valuable it would have to plot the densities per equation and variable + the two constants. This means the plot for a model with 2 variables and 2 lags results in 10 density plots. Now the user would have to specify the exact coefficient of an equation to get only the density plot of it.

**Comment by nk027** [comment]
IIRC the current density method calculates densities of every specified combination of dependents and independents. I.e. for `vars_response = 1` & `vars_impulse = c(1, 3)` it returns a list of the following densities:
- constant on dependent variable 1
- variable 2 (at position 3) on dependent variable 1

Is that not so?
(Whether it makes a lot of sense for interpretation is another question, but why not include it)

**Comment by oDNAudio** [comment]
yep, true. mixed it up with the density plotting function, sorry about that. 

For interpretation it would actually make sense then I think, and if it`s only for visualisation of the posteriors of the coefficients.

**Comment by nk027** [comment]
Nice work!

I removed the option of plotting multiple chains via `plot.bvar_density()` as that option might be confusing and can't be easily accessed via `plot(density(x))`. However, I've moved the functionality to the default plotting function.

Names are now standard.
