### ISSUE TITLE
Implement zero- and sign-restrictions

### ISSUE THREAD

**Issue by nk027** [nk027/bvar#36]
Arias et al. (2018), <https://doi.org/10.3982/ECTA14468>, provide an algorithm for identification via combined zero- (i.e. a no-change expectation instead of no expectation) and sign-restrictions. After implementing the algorithm it should fit rather well into `R/62_sign_restr.R`.

**Comment by oDNAudio** [comment]
This may also be useful (or just easier for us):
[https://eeecon.uibk.ac.at/~breitenlechner/data/Vignette.pdf](url)

**Comment by nk027** [comment]
I had a quick look at the original's replication script and their Matlab routine. I felt like the replication script was rather concise and implementable, but I did not get around to it.

**Comment by nk027** [comment]
Ok, so the way to go might be adding another argument similar to `sign_restr` to `bv_irf()` - there 0s are interpreted as 0 restrictions and NA as no restrictions. Over the next release this should be adapted for `sign_restr` as well.

**Comment by nk027** [comment]
Once we do that we should also rework sign restrictions so they can be imposed at multiple points in time.

**Comment by oDNAudio** [comment]
Closed with bf9b27845d2a0c211f4b69fd5d841eff2b589dd8
