### ISSUE TITLE
Psi

### ISSUE THREAD

**Issue by nk027** [nk027/bvar#37]
- As discussed there's the stationarity question
- If a mode is provided we get an unnecessary warning: `priors[["psi"]][["mode"]] == "auto"`. Should be an easy fix.

**Comment by nk027** [comment]
So now the error message for integrated data reads:
```
    stop("Some of the data appears to be integrated. ",
         "Setting psi automatically via an AR(", lags, ") failed. ",
         "Please provide modes for psi manually (see `?bv_psi`).")
```

We could also just increment the order of integration, but maybe that's too much automation. @oDNAudio, what do you think?

**Comment by oDNAudio** [comment]
I'm not sure either, but we could increment it and issue a warning when doing so (maybe also with the data series for which it had been done)?

This way the user is notified that there may be an issue with integrated but the model would still run through. Then the user can assess the outputs and then decide whether it is necessary to transform the data or not.
