### ISSUE TITLE
Transform a subset of fred_qd to use directly

### ISSUE THREAD

**Issue by nk027** [nk027/bvar#43]
So I can be even lazier when testing.

**Comment by nk027** [comment]
So I worked on adding that. @oDNAudio, can you maybe review `dl_fred_qd.R` whether it works correctly?
Also how should we name the transformed data - just `fred_qd_trans`?

**Comment by oDNAudio** [comment]
Reviewed it, cross-checked a few series and seems to work fine in general.
Changed the way second differences are calculated though.

About the naming, I think `fred_qd_trans` is fine, no need for a fancier name I guess.

**Comment by nk027** [comment]
Danke, sieht deutlich besser aus :100:.
The database is detrended already, right? Cause in the examples we compare the quarters (every 4th) - I skimmed the paper again and maybe that's not necessary?

**Comment by oDNAudio** [comment]
Yes, I think so. In the paper we compute yoy-change rates for some variables, I think the main idea was to enhance interpretability. However, it's not really necessary, that's true.

**Comment by nk027** [comment]
Looking good!
