### ISSUE TITLE
auto_psi

### ISSUE THREAD

**Issue by lucabarbaglia** [nk027/bvar#46]
The auto_psi() function in the file 10_bvar.R, line 176, fit an AR(lags). However, the replication files of Giannone et al. (2015), fit only an AR(1). Wouldn't it be a good option to parametrize also the order of the AR model in the main function? Thanks

**Comment by oDNAudio** [comment]
While it is true that Giannone et al. (2015) fit an AR(1) to obtain the innovations for scaling, we followed common practice in the literature and set it to an AR(lags) for the automated setting of psi (see e.g. Banbura et al. (2010) [ https://doi.org/10.1002/jae.1137](url), Sims and Zha (1998) [https://doi.org/10.2307/2527347](url), Litterman (1986) [https://doi.org/10.2307/2527347](url) )

However, there is an option to provide values for the mode of psi in form of a vector via the argument `mode` in `bv_psi()` manually should there be a need for experimenting without the need of adding another parameter to the functions.

**Comment by lucabarbaglia** [comment]
Ok, thank you!
