### ISSUE TITLE
Rework drawing and storing handling

### ISSUE THREAD

**Issue by oDNAudio** [nk027/bvar#47]
I got the feedback that it's a bit counterintuitive to specify the total number of draws and then the amount of them which are to be discarded instead of specifying the number of saved draws and the ones to burn. 

Also, when `n_draw == n_burn`, an error message stemming from the integer check of `n_thin` pops up at the moment. Whether or not the specification of draws is changed, this should be fixed.

**Comment by nk027** [comment]
I guess we could add an argument for *n_save*. Then we should change the docs for *n_save*, *n_burn*, n_thin* and so on to be more precise.

The issue can be fixed by editing <https://github.com/nk027/bvar/blob/da843f10187b28924d8be8b2485b1aa3a37bfa06/R/10_bvar.R#L126> to `max = n_draw - 1L`.

**Comment by nk027** [comment]
Hey so just fyi @oDNAudio - I removed the `n_save` argument again. As it was implemented before there could have been very annoying problems stemming from the default values. In hindsight it would have been an idea to just go for `n_save` instead of `n_draw`, but what can you do.
