### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by nk027** [nk027/bvar#51]
There's a lot to do to improve the docs:

Document:
- new plotting features from #41 
- transformed FRED-QD from #43 

Also:
- merge some related functionalities
- give better names to items
- rework keywords
- more examples (also see #39)
- improve formatting

**Comment by nk027** [comment]
Done:
- Documented new plotting
- Documented new FRED
- Remove unnecessary method docs
- Small fixes
- Changed some names

To-do:
- Rework keywords
- Go through text of the documentation
- Re-work examples

**Comment by nk027** [comment]
Ok so as of 8af2216 I'd say the only pressing issue is reworking the keywords a bit.

**Comment by oDNAudio** [comment]
One thing we might wanna change is the wording regarding the ML. Now it is called marginalised likelihood in all prints and documentations. We should align this with the text in the paper.
