### ISSUE TITLE
FRED transformation is messy

### ISSUE THREAD

**Issue by nk027** [nk027/bvar#53]
The results of transforming FRED-MD and FRED-QD with `fred_transform()` are rather messy. It seems as if the suggested transformation is applied, but the results are meh. Scaling and lagging may make a difference - also we might want to standardise the result?

**Comment by nk027** [comment]
Apparently Koop, Korobilis and Pettenuzzo (2017) only use codes 1, 4 and 5 although they say that they follow FRED-MD codes. Huber and Feldkircher (2019) only go for log-differences and no transformation.

**Comment by nk027** [comment]
Koop and Korobilis (2013) follow Stock and Watson (2008) and Carriero, Clark and Marcellino (2011) in transforming. Note that these do not directly use FRED-MD.

**Comment by nk027** [comment]
It would be interesting to add transformation codes from multiple sources...

**Comment by oDNAudio** [comment]
I fixed a bug in the transformation as the past version identified the codes wrongly. It should now apply the transformations suggested by McCracken & Ng (2015)

**Comment by oDNAudio** [comment]
I multiplied the series that are differenced with 100 for better interpretability. 
Furthermore, convergence behaviour of the hyperparameters seems to be better (at least for our example)

**Comment by nk027** [comment]
I think this is looking good now, closing. See #56 for what remains open.
