### ISSUE TITLE
IRF horizon

### ISSUE THREAD

**Issue by oDNAudio** [nk027/bvar#55]
We may want to change definition of horizon for the IRFs. 
Right now when we specify `horizon = 12` we actually compute IRFs only 11 periods ahead because our first period is the impact period which should be counted as period 0, right?

**Comment by nk027** [comment]
Good point. However, I think changing this to always be increased by 1 (so there's the full periods) could be rather confusing and does not offer much benefit. Also I am not convinced whether we should change the labels. Maybe it's best to just mention that point 1 is the impact in the documentation.

**Comment by Abhayprag** [comment]
Hello is there a way to darken and broaden the impulse response with a colour other than black? For confidence interval, I am able to change the colour and shade the area as given in the codes. But please let me know is there any way i can change the colur of the impulse response.
![IR](https://user-images.githubusercontent.com/107178791/175007037-cd806c50-b5d4-420c-9593-ade157551479.JPG)
