### ISSUE TITLE
Horizon fevd result

### ISSUE THREAD

**Issue by hp1819** [nk027/bvar#64]
Could the horizon fevd result  of  bvar  similar  to  the fevd result of vars? or How  get the result of the horizon fevd result  of  bvar?

For example, the fevd result of vars is below:
> head(pdata)
          imf_high_epu imf_high_ine imf_high_brent imf_high_wti
2018/4/9        0.1781      -0.0208        -0.0275      -0.0229
2018/4/10      -0.1074      -0.0023         0.0007       0.0007
2018/4/11      -0.0545       0.0059         0.0160       0.0196
2018/4/12       0.1213       0.0376         0.0220       0.0289
2018/4/13       0.0593       0.0173         0.0169       0.0204
2018/4/16      -0.0366       0.0007        -0.0082      -0.0050
> phigh <- VAR(pdata, p=3)
> pfevd <- fevd(phigh, n.head = 10)
> pfevd
$imf_high_epu
      imf_high_epu imf_high_ine imf_high_brent imf_high_wti
 [1,]    1.0000000 0.0000000000    0.000000000  0.000000000
 [2,]    0.9908927 0.0003507713    0.005807697  0.002948813
 [3,]    0.9852992 0.0006634717    0.005762441  0.008274893
 [4,]    0.9835628 0.0025595615    0.005718619  0.008158978
 [5,]    0.9818767 0.0041278389    0.005807536  0.008187937
 [6,]    0.9808208 0.0045709946    0.006316149  0.008292099
 [7,]    0.9806960 0.0046273540    0.006383779  0.008292843
 [8,]    0.9806920 0.0046273738    0.006387598  0.008293064
 [9,]    0.9806415 0.0046358053    0.006423310  0.008299358
[10,]    0.9806177 0.0046452636    0.006436819  0.008300228
...
...

However, I didn't kown how get the result of fevd,  the result is array (dimensions 8000, 4, 10, 4), how can I get the mean result?
could you give me some suggestions or reference?
(the horizon fevd result  of  bvar is below)
> head(p)
          imf_mid_epu imf_mid_ine imf_mid_brent imf_mid_wti
2018/4/9       0.0813     -0.2339       -0.0983     -0.1204
2018/4/10      0.0616     -0.2293       -0.0960     -0.1166
2018/4/11      0.0443     -0.2247       -0.0934     -0.1127
2018/4/12      0.0291     -0.2193       -0.0906     -0.1088
2018/4/13      0.0160     -0.2136       -0.0876     -0.1048
2018/4/16      0.0047     -0.2079       -0.0843     -0.1008
> x <- bvar(p, lags = 5, n_draw = 10000L, n_burn = 2000L, verbose = FALSE)
> irfx <- irf(x, bv_irf(horizon = 10L, identification = FALSE))
> xfevd <- fevd(irfx)
> xfevd
Numeric array (dimensions 8000, 4, 10, 4) of FEVD values from a BVAR.
Computed confidence bands: 16%, 50%, 84%

**Comment by oDNAudio** [comment]
Hi, @hp1819 , you can retrieve **median** of the computed FEVDs by setting `conf_bands = 0.5` in the `fevd()` function and then select the `quants` array from the resulting `bvar_fevd` object, i.e.: 

`xfevd <- fevd(irfx, conf_bands = 0.5)`
`fevd_median <- xfevd$quants`

The slices of the first dimension of this array then hold the median FEVDs for the variables, i.e. `fevd_median[1,,]` gives you the **median** FEVDs for the variable ordered first in your data, `imf_mid_epu` in your example.

Currently we do not feature computing the mean of the FEVDs directly, we will consider adding it in the future.
However, you can do it manually, by using `apply()` on the `fevd` object of `xfevd`, i.e.:

`fevd_mean <- apply(xfevd$fevd, c(2,3,4), mean)`

This object then holds the mean values of the FEVDs and you can access it like the one holding the median values above, i.e. `fevd_mean[1,,]` gives you the **mean** FEVDs for the variable ordered first in your data, `imf_mid_epu` in your example.

Hope this helps!

**Comment by hp1819** [comment]
Thanks for your answer! I get it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nk027/bvar"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月12日(星期一) 下午4:40
收件人:&nbsp;"nk027/bvar"<bvar@noreply.github.com&gt;;
抄送:&nbsp;"王慧"<215492800@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [nk027/bvar] Horizon fevd result (#64)





 
Hi, @hp1819 , you can retrieve median of the computed FEVDs by setting conf_bands = 0.5 in the fevd() function and then select the quants array from the resulting bvar_fevd object, i.e.:
 
xfevd <- fevd(irfx, conf_bands = 0.5)
 fevd_median <- xfevd$quants
 
The slices of the first dimension of this array then hold the median FEVDs for the variables, i.e. fevd_median[1,,] gives you the median FEVDs for the variable ordered first in your data, imf_mid_epu in your example.
 
Currently we do not feature computing the mean of the FEVDs directly, we will consider adding it in the future.
 However, you can do it manually, by using apply() on the fevd object of xfevd, i.e.:
 
fevd_mean <- apply(xfevd$fevd, c(2,3,4), mean)
 
This object then holds the mean values of the FEVDs and you can access it like the one holding the median values above, i.e. fevd_mean[1,,] gives you the mean FEVDs for the variable ordered first in your data, imf_mid_epu in your example.
 
Hope this helps!
