### ISSUE TITLE
Some questions about irf 

### ISSUE THREAD

**Issue by hp1819** [nk027/bvar#65]
Hi，nk027
The following are some questions about irf：
1. irf(x, n_thin = 1L)  
"through change  n_thin can obtain different lag periods impulse response functions" Is that so?

2. How can I get the impulse response number of each variable in different lag periods through the irf function 
Through the below code, I can get the Time point shock response function. 
opt_irf <- bv_irf(horizon = 10, fevd = TRUE)
irfx <- irf(x, opt_irf, conf_bands = 0.5, n_thin = 1L)
However, I don't know how get the impulse response number of each variable in different lag periods through the irf function,
could you give some references

3. Could the irf can get the mean of irf?

**Comment by nk027** [comment]
Hey @hp1819,

1. All `n_thin` does is drop some of the draws. That is useful to speed up calculation.
2. In the `irf[["irf"]]` there is an array with 4 dimensions - (1) draws, (2) responses, (3) horizon, and (4) shocks.
3. This works similarly to fevds (in #64) - you can just `apply` the mean, marginalising the draws in dimension 1.

Much of this is also available in the package documentation (see e.g. `?irf`).

**Comment by hp1819** [comment]
Thanks for your answer. I understand.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nk027/bvar"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 晚上6:42
收件人:&nbsp;"nk027/bvar"<bvar@noreply.github.com&gt;;
抄送:&nbsp;"王慧"<215492800@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [nk027/bvar] Some questions about irf  (#65)





 
Hey @hp1819,
  
All n_thin does is drop some of the draws. That is useful to speed up calculation.
 
In the irf[["irf"]] there is an array with 4 dimensions - (1) draws, (2) responses, (3) horizon, and (4) shocks.
 
This works similarly to fevds (in #64) - you can just apply the mean, marginalising the draws in dimension 1.
  
Much of this is also available in the package documentation (see e.g. ?irf).
