### ISSUE TITLE
Are there any examples that use the Minnesota Prior?

### ISSUE THREAD

**Issue by thestockman27** [nk027/bvar#67]
Hi there,

Thanks for all your work on this package.

I am wondering if you have any working examples that illustrate the use of the Minnesota Prior? I have my own implementation up and running, but it would be beneficial to compare it to something published by the creator of the package.

**Comment by nk027** [comment]
Hey!
Some variant of the prior is always used by the package, so examples using it are in `?bvar` or in the vignette. IIRC correctly these only sample lambda, but not alpha and psi. If that's the issue I can have a look at your code.
Generally you should check out convergence for the sampled parameters and check whether the results given your priors make sense. Regarding the parameters you can also have a look at the Giannone, Lenza, and Primiceri (2015) paper.
