### ISSUE TITLE
Significance test of BVAR coefficient

### ISSUE THREAD

**Issue by hp1819** [nk027/bvar#69]
Hi, nk027

How to obtain the significance test of the BVAR coefficient？
x <- bvar(p_post_two , lags = 8, n_draw = 20000L, n_burn = 5000L, verbose = FALSE)
summary(x)  or coef(x) can't obtain

**Comment by nk027** [comment]
Hey,
I'm not sure what you mean -- it's a Bayesian model and you can get the full posterior of the coefficients. The functions allow you to calculate intervals of the posterior of you want to check overlap with zero.
