### ISSUE TITLE
NA resulting from log?

### ISSUE THREAD

**Issue by nk027** [nk027/bvar#71]
Following comment:

> When running the following Code in Section 4.3

```
run <- bvar(x, lags = 5, n_draw = 50000, n_burn = 25000, n_thin = 1,
priors = priors, mh = mh, verbose = TRUE)

```
> I get the following output including a warning message:
```
Optimisation concluded.
Posterior marginalised likelihood: 3637.405
Hyperparameters: lambda = 1.51378; soc = 0.12618; sur = 0.47674
  |================================| 100%
Finished MCMC after 1.2 mins.
Warning message:
In log(s2) : NaNs produced
```
> I'm running Package BVAR version 1.0.1 with R version 4.0.3. It is worth mentioning that all the outputs I obtain are identical to the ones in the paper. Moreover, I don't get any warning when I run bvar() in Appendix A. Maybe it's just my problem but it is better to double check.

**Comment by nk027** [comment]
I was not able to reproduce this on two machines with R 4.1.0 and 4.0.4.

**Comment by nk027** [comment]
This seems to be a Mac OS specific issue. I was able to pinpoint it to a call of `arima()` in `auto_psi()`. The warning occurs [here](https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/library/stats/R/arima.R#L68):
```r
res <- .Call(C_ARIMA_Like, x, Z, 0L, FALSE)
s2 <- res[1L]/res[3L]
0.5*(log(s2) + res[2L]/res[3L])
```
I'll look into replacing `arima()` with `ar.mle()` for the first call (still need to test). If that fails I think it's fair to let the use dabble with it.

**Comment by nk027** [comment]
I tested the new code with `arima0()` and the warning seems to be gone. However:
- there are small changes to hyperparameter values
- the `arima0()` documentation calls it a preliminary version of `arima()`

I am not 100% sure whether to keep the change just to get rid of a platform-specific non-consequential warning.

In any case, the newest commit 79209a8 improves `auto_psi()` with more verbose messages and a catch for warnings. I am also considering rounding hyperparameters to two digits.

**Comment by zeileis** [comment]
Hi @nk027 and sorry for getting round to this so late...we are handling quite a few papers for the special volume.

I wouldn't switch back to `arima0()` for this as `arima()` is the function to use. Instead I would encourage you to report a minimal, self-contained, and reproducible example. Personally, I think that starting on the R-SIG-Mac mailing list (<https://stat.ethz.ch/mailman/listinfo/r-sig-mac/>) is most promising. They might direct you to R-devel or the Bug reporting system.

The more verbose messages will also be helpful. So my feeling is that no further updates of the package are needed for now. (I'll provide you with a `CITATION` file for the package and ask you for a CRAN update later this month when the special volume is ready to go.)

**Comment by nk027** [comment]
Hey @zeileis,
No worries, I can imagine. That sounds good to me, the verbosity should be fine for users. I will look into drafting a proper bug report, thanks for the reference!

**Comment by nk027** [comment]
Bump, don't forget

**Comment by nk027** [comment]
So the package is adapted accordingly and I posted to the mailing list:

> Dear all,

> There seems to be a small bug with `arima()` on Mac. For some very specific data I get the following warning:
```
Warning message:
In log(s2) : NaNs produced
```
> This seems to stem from `.Call(C_ARIMA_Like, x, Z, 0L, FALSE)` in the `armafn()` objective function. This warning does not occur on Linux or Windows systems or when using the `arima0()` function.
> Below is an example that I hope reproduces (please excuse the dependency, I only encountered it with this data, partly due to my lack of a Mac). Note that the warning in question occurs during estimation, printing always induces a warning.

```r
# install.packages("BVAR")
library("BVAR")

x <- fred_qd[1:243, 
 c("GDPC1", "PCECC96", "GPDIC1", "HOANBS", "GDPCTPI", "FEDFUNDS")]
x <- fred_transform(x, codes = c(4, 4, 4, 4, 4, 1))
Y <- as.matrix(x)[6:nrow(x), ]

ar <- apply(Y, 2, arima, order = c(5, 0, 0)) # Warning only on Mac
ar0 <- apply(Y, 2, arima0, order = c(5, 0, 0)) # No warning
```

> Does anyone have any more information on this? Thanks for the help!

Let's see how this proceeds, but I am assuming it's out of scope for `BVAR` so I'm closing this.
