### ISSUE TITLE
summary bvar

### ISSUE THREAD

**Issue by aroaballesteros** [nk027/bvar#72]
Hello, I am Aroa Ballesteros from Spain, I have run a bvar model but I can not see the summary, I think the problems is when I install package bvartools, apart from summary I have problems to with irf functions, but I have solve them putting BVAR::irf, but it does not work with summary, I do not how to solve this problem.

Thanks in advance for your help

**Comment by oDNAudio** [comment]
Apparently the S3 methods for `summary.bvar` and `predict.bvar` get overwritten by bvartools when loading it. 

An easy fix is to detach bvartools before calling `summary.bvar` on your `bvar` object, i.e.:
`detach("package:bvartools", unload = TRUE)`

**Comment by aroaballesteros** [comment]
Thanl you very much for your answer!!
