### ISSUE TITLE
How to select the number of draws in fevd

### ISSUE THREAD

**Issue by Abhayprag** [nk027/bvar#79]
For getting the fevd in array, what is the number we select for the "draws"? Does it depend on the sample size or anything else? As putting a different number of draws is giving a completely different variance decomposition.

**Comment by nk027** [comment]
Hey, 
if you mean the `n_thin` parameter of the `fevd` method that's just the number of stored draws you want to use to compute FEVDs (i.e. every n'th). So ideally you use the default `n_thin = 1` for low MCMC error, otherwise (with very few draws) the results could have a high variance.

**Comment by Abhayprag** [comment]
"With regards to the fevd object it is an array with dimensions draws x shock x horizon x impact " . 
In this dimension number for "draws"  is dependent on which thing? If i change the number of draws to 1, 10 ,100,200 and so on it gives a different variance decomposition. So on what basis number of draws is decided?
![VDG](https://user-images.githubusercontent.com/107178791/177565124-e0d3a71c-fe50-4007-97f0-9d5eec4b70a7.JPG)

**Comment by nk027** [comment]
Hey, this is estimated with [MCMC methods](https://en.wikipedia.org/wiki/Markov_chain_Monte_Carlo), so these are draws from the posterior. You probably want some posterior summary:
```r
apply(obj$fevd, c(2, 3, 4), mean)
```
