### ISSUE TITLE
Historical Variance Decomposition 

### ISSUE THREAD

**Issue by msh855** [nk027/bvar#81]
Hi, 

Thanks for the package. 

It looks that you do not support a functionality for a Historical variance decomposition. Especially, useful for analysis. 

Is possible, however, to show I someone can use the output from your package to do so manually ? especially as a stacked chart, that shows the percentage contributions of each variable of the target variable y ? 

Thanks

**Comment by nk027** [comment]
Hey Moustafa,

We put this down as an enhancement in #61 (so I'm closing this) – good to know that there's some interest!
In principle it should be straightforward to implement. You can use the respective methods to get the companion form and VCOV, then [this](https://stackoverflow.com/questions/36950491/historical-decomposition-in-r) should be helpful. Also, please do share if you get around to it!

Best,
