### ISSUE TITLE
Sign-restrictions 

### ISSUE THREAD

**Issue by msh855** [nk027/bvar#84]
I get an error when I try to use sign restrictions. 

```

irf(run, opt_irf)
Error in sign_restr(sigma_chol = sigma_chol, sign_restr = sign_restr,  : 
  No matrix fitting the sign restrictions found.
```

Below MWE to reproduce:

```
data = na.omit(data_raw)
data[, names(data[1])] <- as.Date(data[, names(data[1])])  
data = xts(data[, 2:length(colnames(data))], data[, names(data[1])])

keep <- c("X10Y_GER_daily_change", "EUR_Stocks_daily_log_dif","US_Stocks_daily_log_dif","EURUSD_daily_log_dif",  "Spread_yields_daily_change")
data_var = data[,keep]

mn <- bv_minnesota(lambda = bv_lambda(mode = 0.2, sd = 0.4, min = 0.0001, max = 5), alpha = bv_alpha(mode = 2), var = 1e07)
priors <- bv_priors(mn = bv_mn(b = 0))
mh <- bv_metropolis(scale_hess = 0.05, adjust_acc = TRUE, acc_lower = 0.25, acc_upper = 0.45)
run <- bvar(data_var, lags = 5, priors = priors, 
            mh = mh, 
            n_draw = 50000, 
            n_burn = 25000, 
            n_thin = 1,
            verbose = TRUE)

sr <- matrix(c(1, -1, NA, 1, 1, 
               1, 1, NA, 1,1, 
               1,NA,-1,-1,-1,
               1,NA,1,-1,-1,
               1,1,1,1,-1), ncol = 5)


opt_irf <- bv_irf(horizon = 10, identification = TRUE,  sign_restr = sr)
irf_model <-irf(run, opt_irf, conf_bands = c(0.05, 0.16))
```
Attached the raw data 
[bvar_data_raw.csv](https://github.com/nk027/bvar/files/11871154/bvar_data_raw.csv)

**Comment by nk027** [comment]
Hey Moustafa,
This is not an issue with the code, but rather the restrictions in light of the data (and arguably the algorithm to find suitable matrices). If you think the signs ought to work and this is an issue, you can increase the number of draw attempts (from 1000):
```{r}
opt_irf <- bv_irf(horizon = 10, identification = TRUE,  sign_restr = sr, sign_lim = 10000)
```

**Comment by nk027** [comment]
That's interesting - if it doesn't stop early on (no shocks found at all) you can increase the allowed draws further. Otherwise I'll try to have a look.

**Comment by msh855** [comment]
I tried already with a very large number of draws.

I would appreciate if you can test it. I send before the input data and the relevant code.

**Comment by nk027** [comment]
Could it be that the ordering of the variables in Table 1 is off? They list
- restrictive EA & EA LTY
- EA macro & EA equity
- restrictive US & US equity
- US macro & EUR-USD
- Risk & LTY spread

**Comment by msh855** [comment]
Not sure I fully understand what you mean. 

Can you please suggest how the table with the sign restrictions should be ?

**Comment by msh855** [comment]
Updated

The identification strategy worked with the [BEAR toolbox by ECB](https://www.ecb.europa.eu/pub/research/working-papers/html/bear-toolbox.en.html). 

So, it might be the case that Hierarchical BVARs need other configurations or not stable for this problem.

**Comment by nk027** [comment]
They name a **restrictive EA MP shock** as based on German bonds, and a favourable EA macro shock as based on **European stocks**. However, for the US they base a **restrictive MP shock** o **US stocks**. That seems inconsistent?

Interesting, that shouldn't be the case – but gives me something to work with.

**Comment by luisgruber** [comment]
> **Update -------**
> 
> The identification strategy worked with the [BEAR toolbox by ECB](https://www.ecb.europa.eu/pub/research/working-papers/html/bear-toolbox.en.html).
> 
> So, it might be the case that Hierarchical BVARs need other configurations or not stable for this problem.

I don't think that Hierarchical BVARs are not stable for this problem. It seems to me that negative/restrictive shocks are not allowed in the current implementation:
https://github.com/nk027/bvar/blob/14cfbb8b5a2d88f48ea918847359d344834950eb/R/62_sign_restr.R#L88
So, with the sign matrix under consideration,
```
> sr <- matrix(c(1, -1, NA, 1, 1, 
+                1, 1, NA, 1,1, 
+                1,NA,-1,-1,-1,
+                1,NA,1,-1,-1,
+                1,1,1,1,-1), ncol = 5)
> sr
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    1    1    1    1
[2,]   -1    1   NA   NA    1
[3,]   NA   NA   -1    1    1
[4,]    1    1   -1   -1    1
[5,]    1    1   -1   -1   -1
```
it will not be possible finding a matrix fitting the sign restrictons.

Would it be valid to change the signs in the columns with a negative diagonal element, then compute the IRFs and eventually change the signs of the IRFs where one is interested in a restrictive shock? E.g.
```
set.seed(123)
mn <- bv_minnesota(lambda = bv_lambda(mode = 0.2, sd = 0.4, min = 0.0001, max = 5), alpha = bv_alpha(mode = 2), var = 1e07)
priors <- bv_priors(mn = bv_mn(b = 0))
mh <- bv_metropolis(scale_hess = 0.05, adjust_acc = TRUE, acc_lower = 0.25, acc_upper = 0.45)
run <- bvar(data_var, lags = 5, priors = priors, 
            mh = mh, 
            n_draw = 100, 
            n_burn = 90, 
            n_thin = 1,
            verbose = TRUE)
sr_star <- t(t(sr)*c(1,1,-1,-1,-1))
opt_irf <- bv_irf(horizon = 10, identification = TRUE,  sign_restr = sr_star, sign_lim = 50000)
irf_model <-irf(run, opt_irf, conf_bands = c(0.05, 0.16))
irf_model$quants <- aperm(aperm(irf_model$quants,c(4,1,2,3))*c(1,1,-1,-1,-1),c(2,3,4,1))
plot(irf_model)
```

**Comment by nk027** [comment]
Hey, I haven't had time to retrace everything, but figured I'd mention that Lukas updated the sign-restriction algorithm in a branch:
    https://github.com/nk027/bvar/tree/dev_signs
These restrictions seem to work there, but if there's a bug I'm happy for more details or a PR.

*Also, note to self – we really need to test and release these fixed and the HDecomp features.*

**Comment by nk027** [comment]
Had the time to revisit this –
@luisgruber, your approach makes a lot of sense to me.
@msh855, e647054 merges the improvement to how sign restrictions are computed into the main branch – your code runs now – provided you increase `sign_lim = 100000` or somewhere around that. I'm leaving the lower default to avoid users getting stuck waiting, but the error message once it fails due to the limit is now more verbose (also `irf()` now has a `verbose` argument, which can be used to track the progress).
