### ISSUE TITLE
Hyperparameters for monthly data?

### ISSUE THREAD

**Issue by RightHandOfDoom** [nk027/bvar#87]
Hello!

I am a big fan of the BVAR package, it is very helpful.
However, I have a questions: most applications of BVAR focus on quarterly data. 
IIRC, the Giannone et.al paper (2015) uses hyperparameters for alpha and lambda that work well with quarterly data. As far as I recall these are the default values for bv_alpha() and bv_lambda() in BVAR. 

Currently I am working on an application using monthly data (US-CPI, INDPRO, FEDFUNDS, nothing extraordinary). I am curious as to whether there are any best practices regarding the hyperparameter choices for monthly data to make the model work better or whether this is immaterial.

Thank you very much for your help and best regards!

**Comment by nk027** [comment]
Hey,
Thanks for the kind words, glad that you find the package helpful.
That's a good question – it's important to think of the model and priors in the context of the data. In general, the standard setup should work with quarterly and monthly data. However, it may be worth investigating the sensitivity to $\alpha$, which pulls more distant lags closer to the prior mean (the variance is adjusted by $s^{-\alpha}$). For monthly data, you may want less shrinkage than the default value of 2.
You can address this by either fixing alpha somewhere else (just set the `mode` via `bv_alpha()`), or by treating it as a hyperparameter.  For this, just use `bv_priors(hyper = c("lambda", "alpha", "psi"))`, and possibly tweak the range and prior for it.
Hope this helps, let me know if you have any more questions.
Best,
Nikolas
